imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Stoff Doctrine Extension
stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            sluggable: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

#Fos User Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User

ivory_ck_editor:
    input_sync: true
    default_config: base_config
    configs:
        base_config:
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'BulletedList', 'Link'] }
easy_admin:
    site_name: Administration
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    design:
        theme: "default"
        color_scheme: "dark"
        brand_color: "rgba(64,64,64, 0.8)"
        menu:
          - {entity: 'User', label: 'Utilisateurs', icon: 'users'}
          - {entity: 'Category', label: 'Catégories', icon: 'sitemap'}
          - {entity: 'Post', label: 'Contenus', icon: 'file-text-o'}
          - {entity: 'University', label: 'Universités', icon: 'university'}
          - {entity: 'Diploma', label: 'Diplômes', icon: 'graduation-cap'}
          - {entity: 'Professional', label: 'Professionnels', icon: 'briefcase'}
    entities:
        Post:
            class: AppBundle\Entity\Post
            list:
                title: 'Liste des contenus'
            form:
                title: "Créer / Modifier un contenu"
                fields:
                    - { property: 'title', label: 'Titre'}
                    - { property: 'headline', type: 'ckeditor', label: 'Accroche' }
                    - { property: 'content', type: 'ckeditor', label: 'Contenu' }
                    - { property: 'imageUrl', label: "URL de l'image"}
                    - { property: 'type'}
                    - { property: 'parent'}
        User:
            class: AppBundle\Entity\User
            list:
                title: 'Liste des utilisateurs'
        Category:
            class: AppBundle\Entity\Category
            list:
                title: 'Liste des menus'
            form:
                title: "Créer / Modifier un menu"
                fields:
                    - { property: 'position' }
                    - { property: 'label', label: 'Libellé' }
                    - { property: 'route'}
                    - { property: 'parent' }
        Route:
            class: AppBundle\Entity\Route
        Institution:
            class: AppBundle\Entity\Directory\Institution
            form:
                title: "Créer / Modifier une institution"
                fields:
                    - { property: 'name', label: 'Nom'}
                    - { property: 'description', type: 'ckeditor' }
                    - { property: 'address', label: 'Adresse'}
                    - { property: 'phone', label: 'Téléphone'}
                    - { property: 'mobile', label: 'Portable'}
                    - { property: 'email', label: 'Email'}
        Professional:
            class: AppBundle\Entity\Directory\Professional
            list:
                title: 'Liste des professionels'
            form:
                title: "Créer / Modifier un professionnel"
                fields:
                    - { property: 'name', label: 'Nom'}
                    - { property: 'description', type: 'ckeditor' }
                    - { property: 'address', label: 'Adresse'}
                    - { property: 'phone', label: 'Téléphone'}
                    - { property: 'mobile', label: 'Portable'}
                    - { property: 'email', label: 'Email'}
        Diploma:
            class: AppBundle\Entity\Directory\Diploma
            list:
                title: 'Liste des diplômes'
            form:
                title: "Créer / Modifier un diplôme"
                fields:
                    - { property: 'name', label: 'Nom'}
                    - { property: 'description', type: 'ckeditor' }
                    - { property: 'address', label: 'Adresse'}
                    - { property: 'phone', label: 'Téléphone'}
                    - { property: 'mobile', label: 'Portable'}
                    - { property: 'email', label: 'Email'}
        University:
            class: AppBundle\Entity\Directory\University
            list:
                title: 'Liste des universités'
            form:
                title: "Créer / Modifier une université"
                fields:
                    - { property: 'name', label: 'Nom'}
                    - { property: 'description', type: 'ckeditor' }
                    - { property: 'address', label: 'Adresse'}
                    - { property: 'phone', label: 'Téléphone'}
                    - { property: 'mobile', label: 'Portable'}
                    - { property: 'email', label: 'Email'}
