app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"

#fos_user_group:
#    resource: "@FOSUserBundle/Resources/config/routing/group.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

fos_user_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"

fos_user_registration_register:
    path:      /register/
    defaults:  { _controller: FOSUserBundle:Registration:register }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin